---
language: python
dist: xenial
jobs:
  include:
    - stage: test discovery
      python:
        - '3.6'
      services:
        - docker
      install:
        - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} docker.greenkeytech.com
        - python3 -m pip install -r requirements.txt
        - python3 -m pip install -r dev-requirements.txt
      script:
        - set -e
        # validate no duplicate keys in yaml using yamllint
        - python3 -m yamllint .
        # validate black formatting
        - black --check .
        # validate imports are sorted
        - isort --check-only .
        # test all doctests and unittests
        # and discovery sdk examples
        - |-
          export PYTHONPATH=$(pwd)/interpreters:${PYTHONPATH:-}  && \
          USE_BUILT_IN_INTERPRETERS=False && \
          python3 -m pytest --doctest-modules \
            --cov=. --cov-append -v --durations=50 \
            --interpreter-directory=examples \
            --tests $(find examples/*_tests.txt | paste -sd,)
