---
language: python
dist: xenial
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python3 -m pytest .tests/test_all_yaml_files_load.py -s
  - python3 -m pytest --doctest-modules util testing
  - python3 testing/metrics.py
  # validate no duplicate keys in yaml using yamllint
  - python3 -m yamllint .

