---
language: python
dist: xenial
jobs:
  include:
    - stage: test discovery
      python:
        - '3.6'
      services:
        - docker
      install:
        - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS} docker.greenkeytech.com
        - python3 -m pip install -r requirements.txt
        - python3 -m pip install pytest
      script:
        - set -e
        # validate no duplicate keys in yaml using yamllint
        - python3 -m yamllint .
        # test all doctests and unittests
        - |-
          export PYTHONPATH=$(pwd)/interpreters:${PYTHONPATH:-}  && \
          USE_BUILT_IN_INTERPRETERS=False && \
          python3 -m pytest --doctest-modules --cov=. . --durations=50
        - |-
          # test discovery sdk examples
          for file in examples/*/test*.txt; do
            interpreter_directory="$(dirname $file)/custom"
            USE_BUILT_IN_INTERPRETERS=False && \
            python3 test_nlp.py --cov=. --cov-append -v --durations=50 $( [ -d $interpreter_directory ] && echo "--interpreter-directory $interpreter_directory" ) --tests $file
          done
