---
version: "3.7"
# --- local volumes
x-custom:
  &custom
  type: bind
  source: ./custom
  target: /custom
# -------
services:
  # ----------------------------------------------------------------------
  ## FIRST STEP ###
  chat_slack:
    image:
      "docker.greenkeytech.com/chat_slack:${CHAT_SLACK_DOCKER_TAG:-develop}"
    ports:
      - "8003:80" # set ports -> was 8888:80
      ## make a request (curl, python repl) to chat_slack from your workstation /status
      ## then retrieve some chats, and make sure it can return json response with chats
    environment:
      - GKT_USERNAME=gkt
      - GKT_SECRETKEY=5f3d00b5b15884c280a390725a863941a68bfe55
      - GKT_API=https://scribeapi.greenkeytech.com/
      - PORT=80
      - SLACK_API_URL=https://slack.com/api     # SLACK_URL
      - SLACK_ACCESS_TOKEN=xoxp-4953937137-344679330118-509400138422-a20f349799113ba21f5c91e8a190cd14
      - SERVICE_NAME=slack
      - CHANNEL_NAME=ageojo_test
      # need DESTINATION_URL -> sending chats to middleware pipeline (different from current one as does not traverse all microservices
      - DESTINATION_URL=http://discovery/process
    networks:
      - greenkey
  # ----------------------------------------------------------------------
  discovery:
    image:
      "docker.greenkeytech.com/discovery:${DISCOVERY_DOCKER_TAG:-latest}"
    environment:
      - GKT_USERNAME=gkt
      - GKT_SECRETKEY=5f3d00b5b15884c280a390725a863941a68bfe55
      - GKT_API=https://scribeapi.greenkeytech.com/
      - PORT=80
      - NUMBER_OF_INTENTS=2
      - FILE_LOG_LEVEL=debug
#      - DISCOVERY_DOMAINS=broker_quotes     #TODO change from `broker_quotes`
    networks:
      - greenkey
    volumes:
      - <<: *custom
  # ----------------------------------------------------------------------
# ----------------------------------------------------------------------
networks:
  greenkey:
    driver: overlay

